<#
.SYNOPSIS
  Read the endpoint file the PBS job wrote on the HPC, then open the SSH tunnel
  and print the environment variables Claude Code needs.

.EXAMPLE
  ./agent_hpc/local/connect.ps1 -LoginHost login.example.ac.jp -User cs20049

.EXAMPLE
  # just show the endpoint, do not open a tunnel (you open it yourself)
  ./agent_hpc/local/connect.ps1 -LoginHost login.example.ac.jp -ShowOnly
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$LoginHost,
    [string]$User,
    [string]$EndpointFile = '~/.miltoka/agent_endpoint.json',
    [int]$LocalPort = 0,
    [switch]$ShowOnly
)

$ErrorActionPreference = 'Stop'

$target = if ($User) { "$User@$LoginHost" } else { $LoginHost }

Write-Host "reading $EndpointFile from $target ..."
$raw = & ssh $target "cat $EndpointFile"
if ($LASTEXITCODE -ne 0 -or -not $raw) {
    throw "could not read $EndpointFile on $target (is the job running? check: ssh $target qstat -u `$USER)"
}

$ep = ($raw -join "`n") | ConvertFrom-Json

Write-Host ""
Write-Host "job_id : $($ep.job_id)"
Write-Host "status : $($ep.status)"
Write-Host "node   : $($ep.node_host) ($($ep.node_ip))"
Write-Host "port   : $($ep.proxy_port)"
Write-Host "model  : $($ep.model)  (alias: $($ep.model_alias))"
Write-Host ""

if ($ep.status -ne 'ready') {
    Write-Warning "server status is '$($ep.status)', not 'ready' - the model may still be loading."
}

if ($LocalPort -le 0) { $LocalPort = [int]$ep.local_port }
if ($LocalPort -le 0) { $LocalPort = 8787 }

$tunnel = "ssh -N -L ${LocalPort}:$($ep.node_ip):$($ep.proxy_port) $target"
Write-Host "tunnel command:"
Write-Host "  $tunnel"
Write-Host ""
Write-Host "environment for Claude Code (PowerShell):"
Write-Host "  `$env:ANTHROPIC_BASE_URL = 'http://127.0.0.1:$LocalPort'"
Write-Host "  `$env:ANTHROPIC_AUTH_TOKEN = '$($ep.api_key)'"
Write-Host "  `$env:ANTHROPIC_MODEL = '$($ep.model_alias)'"
Write-Host "  `$env:ANTHROPIC_SMALL_FAST_MODEL = '$($ep.model_alias)'"
Write-Host ""

# Drop a sourceable file next to this script so you do not have to copy by hand.
$envPath = Join-Path $PSScriptRoot 'agent_env.ps1'
@(
    "# generated by connect.ps1 - $(Get-Date -Format o)",
    "`$env:ANTHROPIC_BASE_URL = 'http://127.0.0.1:$LocalPort'",
    "`$env:ANTHROPIC_AUTH_TOKEN = '$($ep.api_key)'",
    "`$env:ANTHROPIC_API_KEY = '$($ep.api_key)'",
    "`$env:ANTHROPIC_MODEL = '$($ep.model_alias)'",
    "`$env:ANTHROPIC_SMALL_FAST_MODEL = '$($ep.model_alias)'",
    "`$env:OPENAI_BASE_URL = 'http://127.0.0.1:$LocalPort/v1'",
    "`$env:OPENAI_API_KEY = '$($ep.api_key)'"
) | Set-Content -Path $envPath -Encoding utf8
Write-Host "wrote $envPath  (dot-source it: . ./agent_hpc/local/agent_env.ps1)"

# chat.py picks this up automatically, so it needs no flags.
$jsonPath = Join-Path $PSScriptRoot 'agent_env.json'
[pscustomobject]@{
    openai_base_url = "http://127.0.0.1:$LocalPort/v1"
    anthropic_base_url = "http://127.0.0.1:$LocalPort"
    api_key = $ep.api_key
    model_alias = $ep.model_alias
    model = $ep.model
    job_id = $ep.job_id
} | ConvertTo-Json | Set-Content -Path $jsonPath -Encoding utf8
Write-Host "wrote $jsonPath  (read by chat.py)"

if ($ShowOnly) { return }

Write-Host ""
Write-Host "opening the tunnel (Ctrl+C to close)..."
& ssh -N -L "${LocalPort}:$($ep.node_ip):$($ep.proxy_port)" $target
